name: app_api
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  http: ^1.1.0
  card_swiper: ^3.0.1
  kana_kit: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - image/Wallpaper_1.jpg
    - image/Wallpaper_2.jpg
    - image/Wallpaper_3.gif
    - image/Wallpaper_4.jpg
    - image/Wallpaper_5.jpg
    - image/Yasmin.jpg
    - image/Pacute.jpg
  
  fonts: 
    - family: Alata
      fonts:
        - asset: fonts/Alata-Regular.ttf
    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
    - family: Bungee
      fonts:
        - asset: fonts/Bungee-Regular.ttf
    - family: Dosis
      fonts:
        - asset: fonts/Dosis-VariableFont_wght.ttf
    - family: Gruppo
      fonts:
        - asset: fonts/Gruppo-Regular.ttf
    - family: RubikMonoOne
      fonts:
        - asset: fonts/RubikMonoOne-Regular.ttf
    - family: OverlockSC
      fonts:
        - asset: fonts/OverlockSC-Regular.ttf
    



